### ISSUE TITLE
Great app

### ISSUE THREAD

**Issue by Butterfly-Dragon** [eirikb/AudibleHero#5]
Would be useful however to have a couple more features:
- A filter to ignore copies of the same books i already own in a series (yes there could be newer and better recorded versions, but most of the times i tend to ignore them)
+- Related to the above, but a lot harder to do... omnibuses (example: i bought an omnibus of books 1 to 3 of a series of 5 and i'm not interested in getting shown new versions of said books 1 to 3, and vice versa i got books 1 through 3... but now an omnibus came out collecting them... though luck... i should have waited... but i'd like not to be reminded of the annoying fact.)
- A way to filter out a series i'm not interested into anymore.

Let me know if it's feasible. Aside from the two above this was something i've been waiting for a long time. up until now i had to do it manually via countless bookmarks to each series. 😉👍

**Comment by eirikb** [comment]
Hi

1. This should be possible to do. There are two ways to do this:
    1. Remove/hide based on copy number, if you own a book in the same series with the same number then books with same number could be hidden.
     Good: It will most likely always work.
    1. Remove all books with a title identical to one you already own (not by series, but in total).
    Good: It will remove books not in series which you already own, which will be helpful when looking at new books in general. Bad: Might not always work.
1. This was a feature we had before, it was possible to "ignore" a whole series and/or book. It was a nice feature, but sometimes it would mess up, because the values were stored somewhere else than books. For instance now you can clear cache, which will remove all stored data, but then ignored books must not be clear. And ignored books must be synced between devices.

For 1 I could probably do the first, it should be easy to implement.  
For 2 I could try re-introducing the synced data store. I have re-written how data is stored, so I might be able to make it work much better now. The reason it didn't work properly before wasn't because of the tech, but my lousy programming.

**Comment by Butterfly-Dragon** [comment]
Wow, that was quick. 😁👍

- I agree copy number seems to be the best option, since nowadays finally the series get numbered. Sometimes the same copy also has a different title, and sometimes books with the same title tend to crop up in different series. So "title based" seems suboptimal at best.

- While it would be wonderful to have the ignored books be synced on all devices for now i'm not bothered by having just one main device where i check the book series and decide what to ignore, i'm not the kind of guy that need to have everything synced everywhere. Given what you just said if this data is stored locally you could provide an option, upon clearing cache, to not clear the ignored series or to clear only the ignored series. Also this should be a "filter" option so that i can choose to show the ignored ones or show both the ignored and unignored, much like all the other filters work.

**Comment by eirikb** [comment]
Answering is easy, actually coding it is another story :wink: 

I'll do the by-number approach for 1.

I can add ignoring of books with storing locally, which would be much safer, and I can store it alongside books so it won't be cleared when clearing cache. But I'm not sure how good that would be, as un-synced state will eventually be lost (be it another devide, re-install or Chrome crashes). The synced approach sounds very complicated, but it's actually a feature in Chrome extensions, each extension can sync some data to the Google account. I'll look into it, if it's too much hassle I'll store the data locally :smile: 

Can't guarantee when I can get around to work on these things

**Comment by Butterfly-Dragon** [comment]
ehy! can't complain about free stuff being late i'm already thanking you a lot that's there in the first place.

🤔 Okay... maybe i haven't voiced it aloud.

**THANKS!** 😁👍👏🎉🎊

**Comment by Butterfly-Dragon** [comment]
On a side note about this being free if you have a paypal or something where i can send you some beer&pizza money as an extra thank you, let me know.

**Comment by eirikb** [comment]
Just released a new version (19) which has the two things we talked about.  
It might need some fine tuning, and the description of the filters is horrible, but I think it might do what you asked for. Ignoring is only per book for now, so that is a bit cumbersome. The old version of AudibleHero was book, per series, or everything visible, perhaps everything visible could be an option. Caching is only local, not synced.

About donations I'd prefer not to get any, if that is ok. But I appreciate the sentiment :)

**Comment by Butterfly-Dragon** [comment]
Ah, well, i tried, still, thank you very much. Let's seeeeeee...

🤔 what's all these "false" i'm reading? I.... think you might be showing a flag value there. 😅

also... it does hide some books, but it's still fiddly. for example here...
![image](https://user-images.githubusercontent.com/33538906/46502363-419f3500-c828-11e8-89c5-8213b5ceefe0.png)
we see that "the wee free" men are among the unhidden books, but as you can see here...
![image](https://user-images.githubusercontent.com/33538906/46502443-71e6d380-c828-11e8-99df-2dca8c85ca31.png)
i do have that book in the series. 🤔

meh... i hid everything manually, it did not need much work. Thanks 👍

**Comment by Butterfly-Dragon** [comment]
one last request: ordering by series name and numbered order within series. thank you very much.

**Comment by Butterfly-Dragon** [comment]
Meh, as i said. The fact i could individually search a series and hide individual books already helped a lot in making order. I went from a mess of 272 books to 90 which i know i want to check. There still are some parsing errors, but seriously, Already this little helped quite a lot. The fact that the parser makes some mistakes (it does indeed also hide 2 books i don't have... because they are "unnumbered" and so they end up in the same "number" 🤣) is a very minor gripe, because finally i do have a way to finally skim it to what's important. So... thank you very much. 😁👍

**Comment by eirikb** [comment]
Great stuff. I'm closing this now.
I'm not sure if I'm going to do the ordering thing you mentioned earlier. Maybe later.

Oh and about the parsing (in general), it's manual scraping of the audible pages. It's not easy, or stable, but it's the best I can do :smiley: 

Also, I pushed a new version without `false` and with an (hopefully) improved way of parsing series number.
